# Generated by Django 2.2.6 on 2019-10-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_accesorios', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.DateTimeField(max_length=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_celulares', models.CharField(max_length=10)),
                ('codigo', models.FloatField()),
                ('marca', models.CharField(max_length=25)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('serie_imei', models.DateTimeField(auto_now_add=True)),
                ('precio_mayor', models.FloatField()),
                ('precio_unidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Chips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chips', models.CharField(max_length=10)),
                ('codigo', models.FloatField()),
                ('operador', models.CharField(max_length=15)),
                ('serie', models.CharField(max_length=8)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('DPI', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_detalle_venta', models.CharField(max_length=7)),
                ('accesorios_id_accesorios', models.CharField(max_length=10)),
                ('ventas_id_ventas', models.CharField(max_length=10)),
                ('reparaciones_idreparaciones', models.CharField(max_length=10)),
                ('chips_id_Chips', models.CharField(max_length=10)),
                ('celulares_id_Celulares', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reparaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reparaciones', models.CharField(max_length=7)),
                ('descripcion_falla', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_repuestos', models.CharField(max_length=7)),
                ('codigo', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=25)),
                ('cantidad', models.FloatField()),
                ('precio_mayor', models.FloatField()),
                ('precio_unidad', models.FloatField()),
                ('reparaciones_idReparaciones', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Usuario', models.CharField(max_length=7)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('empleados_id_empleados', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleados', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('DPI', models.CharField(max_length=30)),
                ('telefono', models.FloatField()),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Ventas', models.CharField(max_length=7)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_venta', models.FloatField()),
                ('vendedor_id_vendedor', models.CharField(max_length=7)),
                ('cliente_id_cliente', models.CharField(max_length=7)),
                ('empleados_id_empleados', models.CharField(max_length=7)),
            ],
        ),
    ]
