# Generated by Django 2.2.5 on 2019-10-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idaccesorios', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.DateTimeField(auto_now_add=True)),
                ('fechaingreso', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.FloatField()),
            ],
        ),
    ]
