# Generated by Django 2.2.6 on 2019-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_auto_20191005_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='marca',
            field=models.DateTimeField(max_length=True),
        ),
    ]
