# Generated by Django 2.2.6 on 2019-10-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_auto_20191005_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accesorios',
        ),
        migrations.DeleteModel(
            name='Celulares',
        ),
        migrations.DeleteModel(
            name='Chips',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Detalle_Venta',
        ),
        migrations.DeleteModel(
            name='Reparaciones',
        ),
        migrations.DeleteModel(
            name='Repuestos',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
